import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DocumentHead from "@/ui/Document";
import NavBar from "@/ui/components/NavBar/NavBar";
import { ModalProvider } from "@/ui/components/Modal/Modal";
import { ReduxProvider } from "@/store/provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <DocumentHead />

      <body
        className={`${geistSans.variable} ${geistMono.variable} w-screen h-screen relative antialiased`}
      >
        <ReduxProvider>
          <ModalProvider>{children}</ModalProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
