export const portfolioSectionQuery = `*[_type == "portfolio"]{
  portfolioSection{
    description,
    heading[]{
      text,
      type
    },
    headline,
    "projects":[visibility==true]{
      excerpt,
      slug,
      tags,
      thumbnail,
      title,
      tools,
      url,
      meta{
        title,
        description,
        keywords,
        canonicalUrl,
        ogTitle,
        ogDescription,
        ogImage,
        twitterTitle,
        twitterDescription,
        twitterImage,
        structuredData
      }
    }
  }
}
`;

export const portfolioQuery = `*[_type == "portfolio"]{
  _id,
  _createdAt,
  _updatedAt,
  _rev,
  _type,
  meta{
    title,
    description,
    keywords,
    canonicalUrl,
    robots,
    ogTitle,
    ogDescription,
    ogImage,
    twitterTitle,
    twitterDescription,
    twitterImage,
    structuredData
  },
  about{
    badgeIcon,
    badgeLabel,
    content,
    email,
    experiences[]{
      duration,
      label
    },
    heading[]{
      text,
      type
    },
    headline,
    image,
    phone,
    topStatLabel,
    topStatValue
  },
  contact{
    emailPlaceholder,
    messagePlaceholder,
    namePlaceholder,
    submitLabel,
    subtitle,
    tagline,
    title
  },
  educationWorkSection{
    heading[]{
      text,
      type
    },
    headline,
    education[]{
      duration,
      name,
      title
    },
    work[]{
      duration,
      name,
      title
    }
  },
  hero{
    badgesGroup[],
    followText,
    heading[]{
      text,
      type
    },
    headline,
    heroImage,
    primaryCta,
    quote,
    reviews,
    secondaryCta,
    socials[],
    subtext
  },
  "portfolioSection": portfolioSection[visibility == true]{
    description,
    heading[]{
      text,
      type
    },
    headline,
    projects[]{
      excerpt,
      slug,
      tags,
      thumbnail,
      title,
      tools,
      url,
      meta{
        title,
        description,
        keywords,
        canonicalUrl,
        ogTitle,
        ogDescription,
        ogImage,
        twitterTitle,
        twitterDescription,
        twitterImage,
        structuredData
      }
    }
  },
  pricingSection{
    heading[]{
      text,
      type
    },
    headline,
    plans[]{
      duration,
      features,
      highlight,
      name,
      price
    }
  },
  servicesSection{
    heading[]{
      text,
      type
    },
    headline,
    intro,
    items[]{
      description,
      image,
      index,
      label,
      tags
    }
  },
  technologiesSection{
    heading[]{
      text,
      type
    },
    headline,
    items[]{
      icon,
      name,
      proficiency
    }
  },
  testimonialsSection{
    heading[]{
      text,
      type
    },
    headline,
    testimonials[]{
      avatar,
      feedback,
      name,
      rating,
      role
    }
  }
}
`;
  
